os: osx
osx_image: xcode11.3
language: swift
env:
  - SDK=iphonesimulator13.2 DESTINATION="OS=12.0,name=iPhone XS"

script: xcodebuild clean build test -project RCC.xcodeproj -scheme "RCC" -sdk "$SDK" -destination "$DESTINATION" CODE_SIGNING_REQUIRED=NO
