os: osx
osx_image: xcode11.3
language: swift

script: xcodebuild clean build test -workspace RCC.xcworkspace -scheme "RCC" -sdk "iphonesimulator13.2" -destination "OS=12.0,name=iPhone XS" CODE_SIGNING_REQUIRED=NO
